import {
  Cloud as CloudIcon,
  Cpu as CpuIcon,
  Gauge as GaugeIcon,
  HardDrive as HardDriveIcon,
  Laptop as LaptopIcon,
  Monitor as MonitorIcon,
  Server as ServerIcon,
} from '@keyline-icons/react/fill';
import type { Machine } from './Machine';

const MACHINES: readonly Machine[] = [
  {
    id: 'intel-mini-pc',
    name: 'An Intel mini PC',
    examples: 'Intel N100 or N150 boxes, NUCs and other recent Core i3 to i7 machines',
    acceleration: 'QuickSync, through VAAPI or QSV',
    support: 'image',
    body: 'The most common Valence server. The image carries Intel’s own media driver, so passing /dev/dri through is all it takes. Recent Intel graphics decode HEVC 10-bit and AV1 in hardware, which covers most modern releases.',
    guide: '/install/hardware-transcoding#intel-and-amd',
    icon: CpuIcon,
  },
  {
    id: 'nas',
    name: 'A NAS that runs Docker',
    examples: 'Synology, QNAP, Unraid or TrueNAS on an x86 processor',
    acceleration: 'QuickSync or VAAPI where the processor has Intel or AMD graphics',
    support: 'image',
    body: 'Anything that takes a compose file runs the stack, with the library mounted read-only by default. A model with Intel graphics can pass /dev/dri through for hardware transcoding. NAS units built on ARM processors can’t run the published image.',
    guide: '/install/storage-and-volumes',
    icon: HardDriveIcon,
  },
  {
    id: 'intel-arc',
    name: 'An Intel Arc graphics card',
    examples: 'Arc A310, A380 and newer, in any Linux box',
    acceleration: 'QuickSync, with AV1 encoding',
    support: 'image',
    body: 'A cheap card that adds a strong encoder to a server with weak or no graphics of its own. It goes through /dev/dri like Intel’s built-in graphics, and it can encode AV1 as well as H.264 and HEVC.',
    guide: '/install/hardware-transcoding#machines-with-more-than-one-card',
    icon: GaugeIcon,
  },
  {
    id: 'amd',
    name: 'AMD Radeon or a Ryzen with graphics',
    examples: 'Radeon cards, and Ryzen processors with built-in graphics, on Linux',
    acceleration: 'VAAPI, through the bundled radeonsi driver',
    support: 'image',
    body: 'Works in the container through /dev/dri with the driver the image already carries. AMF, AMD’s other encoder, needs the proprietary driver and is only used when the transcoder runs natively on Windows.',
    guide: '/install/hardware-transcoding#intel-and-amd',
    icon: MonitorIcon,
  },
  {
    id: 'nvidia',
    name: 'An NVIDIA graphics card',
    examples: 'GeForce, RTX and Quadro cards',
    acceleration: 'NVENC',
    support: 'setup',
    body: 'The encoder is in the bundled FFmpeg, but the container needs the NVIDIA Container Toolkit on the host to reach the card, and the shipped compose file doesn’t configure it yet. On Windows, running the transcoder natively uses NVENC directly.',
    guide: '/install/hardware-transcoding#nvidia',
    icon: GaugeIcon,
  },
  {
    id: 'mac',
    name: 'A Mac with Apple silicon',
    examples: 'Mac mini, Mac Studio or any M-series Mac',
    acceleration: 'VideoToolbox',
    support: 'native',
    body: 'Docker Desktop runs the stack, but a container on a Mac can’t reach the video hardware. So the transcoder runs natively on the Mac, using VideoToolbox, and everything else stays in Docker.',
    guide: '/install/hardware-transcoding-on-a-mac',
    icon: LaptopIcon,
  },
  {
    id: 'windows',
    name: 'A Windows PC',
    examples: 'Any x86 Windows machine with Intel, AMD or NVIDIA graphics, or a Snapdragon Windows on Arm laptop',
    acceleration: 'QuickSync, AMF, NVENC or Media Foundation',
    support: 'native',
    body: 'Docker Desktop runs the stack. Inside the container only NVIDIA’s encoder can be reached, so the transcoder runs natively on Windows to use Intel, AMD or NVIDIA graphics, and Media Foundation on Windows on Arm.',
    guide: '/install/hardware-transcoding-on-windows',
    icon: MonitorIcon,
  },
  {
    id: 'no-gpu',
    name: 'A machine with no graphics',
    examples: 'A virtual machine, a cloud server, or an older desktop',
    acceleration: 'None. Transcodes run on the processor',
    support: 'software',
    body: 'Everything still works. Anything a device can play directly costs almost nothing; what it can’t is converted on the processor, which is far more work. Size the processor for the transcodes you expect, and fewer for 4K or HDR.',
    guide: '/start/system-requirements#transcoding-load',
    icon: CloudIcon,
  },
  {
    id: 'arm-boards',
    name: 'A Raspberry Pi or other ARM board',
    examples: 'Raspberry Pi, and Rockchip boards such as the Orange Pi 5',
    acceleration: 'RKMPP on Rockchip, in the transcoder',
    support: 'notYet',
    body: 'The published image is built for x86-64 only, so ARM boards can’t run it yet. The transcoder already knows Rockchip’s encoder, ready for when an ARM image ships.',
    guide: null,
    icon: ServerIcon,
  },
];

export { MACHINES };
