packages:
  - 'apps/desktop'
  - 'apps/landing'
  - 'apps/web'
  - 'apps/server'
  - 'apps/requests'
  - 'apps/transcoder'
  - 'packages/*'
  - 'tools'

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
