import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const BRICKS: OrbVariant = {
  key: 'bricks',
  label: say('ui.variants.bricks.bricks'),
  shader: say('ui.variants.bricks.defineSTEPS96Vec3LgCellFloat'),
  params: [
    {
      key: 'spin',
      label: say('common.spin'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.25,
      isRate: true,
    },
    { key: 'tilt', label: say('common.tilt'), min: 0, max: 4, step: 0.02, standard: 0.55 },
    {
      key: 'rebuild',
      label: say('ui.variants.bricks.rebuildRate'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 0.4,
      isRate: true,
    },
    {
      key: 'gap',
      label: say('ui.variants.bricks.missingBricks'),
      min: 0,
      max: 0.8,
      step: 0.01,
      standard: 0.07,
    },
    {
      key: 'studs',
      label: say('ui.variants.bricks.studs'),
      min: 8,
      max: 48,
      step: 1,
      standard: 18,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.95 },
    {
      key: 'patch',
      label: say('ui.variants.bricks.colourPatches'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.35,
    },
    {
      key: 'stud',
      label: say('ui.variants.bricks.studRelief'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.85,
    },
    {
      key: 'seam',
      label: say('ui.variants.bricks.seams'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.6,
    },
    {
      key: 'gloss',
      label: say('ui.variants.bricks.gloss'),
      min: 0,
      max: 3,
      step: 0.02,
      standard: 1,
    },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 3, step: 0.015, standard: 1 },
    { key: 'gain', label: say('common.gain'), min: 0.05, max: 5, step: 0.05, standard: 1 },
    { key: 'contrast', label: say('common.contrast'), min: 0.15, max: 10, step: 0.05, standard: 1 },
  ],
  colours: [
    { key: 'brickA', label: say('common.red'), standard: '#c4281c' },
    { key: 'brickB', label: say('common.yellow'), standard: '#f2cd37' },
    { key: 'brickC', label: say('ui.variants.bricks.blue'), standard: '#1e5aa8' },
    { key: 'brickD', label: say('common.green'), standard: '#00852b' },
    { key: 'brickE', label: say('common.white'), standard: '#f4f4f4' },
  ],
};

export { BRICKS };
