import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const CAUSTICS: OrbVariant = {
  key: 'caustics',
  label: say('ui.variants.caustics.caustics'),
  shader: say('ui.variants.caustics.floatCausticWarpVec2FoldVec2P'),
  params: [
    {
      key: 'flow',
      label: say('ui.variants.caustics.waterFlow'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 0.92,
      isRate: true,
    },
    {
      key: 'spin',
      label: say('common.turn'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.09,
      isRate: true,
    },
    {
      key: 'swellRate',
      label: say('ui.variants.caustics.surgeRate'),
      min: 0,
      max: 8,
      step: 0.05,
      standard: 0.6,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    {
      key: 'scale',
      label: say('ui.variants.caustics.netScale'),
      min: 3,
      max: 30,
      step: 0.1,
      standard: 9,
    },
    {
      key: 'warp',
      label: say('ui.variants.caustics.rippleDepth'),
      min: 0,
      max: 3,
      step: 0.02,
      standard: 0.8,
    },
    {
      key: 'edge',
      label: say('ui.variants.caustics.lineSharpness'),
      min: 0.5,
      max: 10,
      step: 0.05,
      standard: 3,
    },
    {
      key: 'split',
      label: say('ui.variants.caustics.colourFringe'),
      min: 0,
      max: 3,
      step: 0.02,
      standard: 0.6,
    },
    {
      key: 'swell',
      label: say('ui.variants.caustics.surgeDepth'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.15,
    },
    {
      key: 'gain',
      label: say('ui.variants.caustics.sunPower'),
      min: 0.05,
      max: 6,
      step: 0.05,
      standard: 6,
    },
    {
      key: 'contrast',
      label: say('ui.variants.caustics.toneKnee'),
      min: 0.15,
      max: 6,
      step: 0.05,
      standard: 1.3,
    },
    {
      key: 'light',
      label: say('ui.variants.caustics.floorLight'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 0.9,
    },
    { key: 'rim', label: say('common.rimSheen'), min: 0, max: 3, step: 0.015, standard: 0.6 },
  ],
  colours: [
    { key: 'deep', label: say('common.water'), standard: '#6f0b0b' },
    { key: 'sun', label: say('ui.variants.caustics.causticLight'), standard: '#7ff6ff' },
    { key: 'sheen', label: say('common.sheen'), standard: '#bfe8ff' },
  ],
};

export { CAUSTICS };
