import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const CLOUD: OrbVariant = {
  key: 'cloud',
  label: say('common.cloud'),
  shader: say('ui.variants.cloud.defineSTEPS56DefineLIGHTSTEPS'),
  params: [
    {
      key: 'speed',
      label: say('common.animSpeed'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 10,
      isRate: true,
    },
    {
      key: 'camDist',
      label: say('common.cameraDistance'),
      min: 0.5,
      max: 40,
      step: 0.2,
      standard: 4.4,
    },
    { key: 'focal', label: say('common.lens'), min: 0.3, max: 15, step: 0.1, standard: 1.8 },
    {
      key: 'radius',
      label: say('ui.variants.cloud.cloudRadius'),
      min: 0.15,
      max: 10,
      step: 0.05,
      standard: 2,
    },
    { key: 'scale', label: say('common.cloudScale'), min: 0.1, max: 15, step: 0.1, standard: 0.8 },
    { key: 'churn', label: say('common.churn'), min: 0, max: 5, step: 0.03, standard: 0.3 },
    {
      key: 'threshold',
      label: say('common.clumping'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 0.075,
    },
    {
      key: 'edgeSoft',
      label: say('ui.variants.cloud.edgeSoftness'),
      min: 0.1,
      max: 10,
      step: 0.05,
      standard: 0.8,
    },
    {
      key: 'density',
      label: say('ui.variants.cloud.density'),
      min: 0.03,
      max: 20,
      step: 0.1,
      standard: 3.2,
    },
    {
      key: 'absorb',
      label: say('ui.variants.cloud.absorption'),
      min: 0.03,
      max: 15,
      step: 0.1,
      standard: 1.4,
    },
    {
      key: 'shadowAbsorb',
      label: say('ui.variants.cloud.shadowDepth'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 2.4,
    },
    {
      key: 'shadowLift',
      label: say('ui.variants.cloud.shadowLift'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.55,
    },
    {
      key: 'aniso',
      label: say('ui.variants.cloud.forwardScatter'),
      min: -0.9,
      max: 0.9,
      step: 0.01,
      standard: 0.45,
    },
    {
      key: 'lightSpin',
      label: say('ui.variants.cloud.lightOrbit'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 0.12,
    },
    {
      key: 'power',
      label: say('ui.variants.cloud.lightPower'),
      min: 0.03,
      max: 40,
      step: 0.2,
      standard: 1.9,
    },
    {
      key: 'ambient',
      label: say('ui.variants.cloud.ambient'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 0.12,
    },
    { key: 'exposure', label: say('common.exposure'), min: 0.03, max: 10, step: 0.05, standard: 1 },
    {
      key: 'alphaGain',
      label: say('common.alphaGain'),
      min: 0.05,
      max: 10,
      step: 0.05,
      standard: 1.5,
    },
  ],
  colours: [
    { key: 'light', label: say('common.light'), standard: '#ffd7a3' },
    { key: 'shadow', label: say('common.shadow'), standard: '#3a4a8c' },
  ],
};

export { CLOUD };
