import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const GALAXY: OrbVariant = {
  key: 'galaxy',
  label: say('ui.variants.galaxy.galaxy'),
  shader: say('ui.variants.galaxy.defineSTEPS56DefineTURBOCT'),
  params: [
    {
      key: 'spin',
      label: say('ui.variants.galaxy.discTurn'),
      min: 0,
      max: 3,
      step: 0.01,
      standard: 0.06,
      isRate: true,
    },
    {
      key: 'churn',
      label: say('ui.variants.galaxy.gasChurn'),
      min: 0,
      max: 5,
      step: 0.02,
      standard: 0.25,
      isRate: true,
    },
    {
      key: 'beat',
      label: say('ui.variants.galaxy.coreBeat'),
      min: 0,
      max: 12,
      step: 0.05,
      standard: 0.8,
      isRate: true,
    },
    {
      key: 'twinkle',
      label: say('common.twinkleRate'),
      min: 0,
      max: 12,
      step: 0.05,
      standard: 1.2,
      isRate: true,
    },
    {
      key: 'camDist',
      label: say('common.cameraDistance'),
      min: 1,
      max: 50,
      step: 0.3,
      standard: 7,
    },
    { key: 'focal', label: say('common.lens'), min: 0.15, max: 15, step: 0.05, standard: 2.25 },
    {
      key: 'envRadius',
      label: say('ui.variants.galaxy.envelopeRadius'),
      min: 0.15,
      max: 15,
      step: 0.1,
      standard: 2.6,
    },
    {
      key: 'tilt',
      label: say('ui.variants.galaxy.tilt0EdgeOn'),
      min: 0,
      max: 1.5,
      step: 0.01,
      standard: 0.85,
    },
    {
      key: 'arms',
      label: say('ui.variants.galaxy.armCount'),
      min: 1,
      max: 6,
      step: 1,
      standard: 2,
    },
    {
      key: 'wind',
      label: say('ui.variants.galaxy.armWinding'),
      min: 0,
      max: 8,
      step: 0.05,
      standard: 3.4,
    },
    {
      key: 'ragged',
      label: say('ui.variants.galaxy.armFray'),
      min: 0,
      max: 12,
      step: 0.05,
      standard: 3,
    },
    {
      key: 'armSharp',
      label: say('ui.variants.galaxy.armSharpness'),
      min: 0.3,
      max: 8,
      step: 0.05,
      standard: 2.2,
    },
    {
      key: 'falloff',
      label: say('ui.variants.galaxy.discFalloff'),
      min: 0.3,
      max: 12,
      step: 0.05,
      standard: 1.7,
    },
    {
      key: 'thick',
      label: say('ui.variants.galaxy.discThickness'),
      min: 0.01,
      max: 1,
      step: 0.005,
      standard: 0.035,
    },
    {
      key: 'bulge',
      label: say('ui.variants.galaxy.coreTightness'),
      min: 2,
      max: 200,
      step: 1,
      standard: 40,
    },
    {
      key: 'core',
      label: say('ui.variants.galaxy.coreDensity'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 5,
    },
    {
      key: 'turbScale',
      label: say('ui.variants.galaxy.turbulenceScale'),
      min: 0.5,
      max: 30,
      step: 0.1,
      standard: 9,
    },
    { key: 'threshold', label: say('common.clumping'), min: 0, max: 1, step: 0.01, standard: 0.35 },
    {
      key: 'density',
      label: say('ui.variants.galaxy.gasDensity'),
      min: 0.1,
      max: 40,
      step: 0.1,
      standard: 14,
    },
    {
      key: 'absorb',
      label: say('ui.variants.galaxy.dustAbsorption'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 3.5,
    },
    {
      key: 'stars',
      label: say('ui.variants.galaxy.stars'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 1.2,
    },
    {
      key: 'starDensity',
      label: say('ui.variants.galaxy.starDensity'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.5,
    },
    {
      key: 'starScale',
      label: say('ui.variants.galaxy.starScale'),
      min: 5,
      max: 200,
      step: 1,
      standard: 48,
    },
    {
      key: 'hueReach',
      label: say('ui.variants.galaxy.hueReach'),
      min: 0.15,
      max: 1.5,
      step: 0.01,
      standard: 0.6,
    },
    {
      key: 'pulse',
      label: say('ui.variants.galaxy.beatDepth'),
      min: 0,
      max: 3,
      step: 0.01,
      standard: 0.2,
    },
    {
      key: 'breathe',
      label: say('ui.variants.galaxy.discBreathing'),
      min: 0,
      max: 2,
      step: 0.01,
      standard: 0,
    },
    {
      key: 'exposure',
      label: say('common.exposure'),
      min: 0.05,
      max: 50,
      step: 0.05,
      standard: 1.1,
    },
    {
      key: 'contrast',
      label: say('common.contrast'),
      min: 0.15,
      max: 6,
      step: 0.05,
      standard: 1.15,
    },
    {
      key: 'saturation',
      label: say('common.saturation'),
      min: 0,
      max: 4,
      step: 0.02,
      standard: 1.35,
    },
    {
      key: 'alphaGain',
      label: say('common.alphaGain'),
      min: 0.05,
      max: 15,
      step: 0.1,
      standard: 2,
    },
    {
      key: 'fill',
      label: say('ui.variants.galaxy.nightFill'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.85,
    },
    { key: 'rim', label: say('common.rimLight'), min: 0, max: 3, step: 0.015, standard: 0.35 },
    { key: 'edge', label: say('common.edgeSharpness'), min: 0, max: 1, step: 0.01, standard: 1 },
    {
      key: 'edgeFade',
      label: say('ui.variants.galaxy.haloFalloff'),
      min: 0.1,
      max: 3,
      step: 0.015,
      standard: 0.98,
    },
  ],
  colours: [
    { key: 'tint', label: say('common.tint'), standard: '#ffffff' },
    { key: 'core', label: say('common.core'), standard: '#fff3d6' },
    { key: 'inner', label: say('ui.variants.galaxy.innerArms'), standard: '#7fb4ff' },
    { key: 'outer', label: say('ui.variants.galaxy.outerArms'), standard: '#c46bff' },
    { key: 'deep', label: say('ui.variants.galaxy.night'), standard: '#04050f' },
    { key: 'rim', label: say('common.rim'), standard: '#8fb0ff' },
  ],
};

export { GALAXY };
