import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const LED_WALL: OrbVariant = {
  key: 'ledWall',
  label: say('ui.variants.ledWall.lEDWall'),
  shader: say('ui.variants.ledWall.voidMainFloatCoverNowUPCoverage'),
  params: [
    {
      key: 'drift',
      label: say('common.drift'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.45,
      isRate: true,
    },
    {
      key: 'churn',
      label: say('common.churn'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.5,
      isRate: true,
    },
    {
      key: 'swirl',
      label: say('ui.variants.ledWall.fluidity'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 1.2,
    },
    {
      key: 'shuffle',
      label: say('common.shuffle'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 0.6,
      isRate: true,
    },
    { key: 'pulse', label: say('common.pulseDepth'), min: 0, max: 2, step: 0.01, standard: 0 },
    {
      key: 'spin',
      label: say('common.roll'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.1,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    {
      key: 'cells',
      label: say('ui.variants.ledWall.tileGrid'),
      min: 16,
      max: 160,
      step: 2,
      standard: 48,
    },
    {
      key: 'scale',
      label: say('ui.variants.ledWall.blobScale'),
      min: 0.3,
      max: 10,
      step: 0.1,
      standard: 1.3,
    },
    {
      key: 'coverage',
      label: say('ui.variants.ledWall.coverage'),
      min: 0,
      max: 1.2,
      step: 0.01,
      standard: 0.52,
    },
    {
      key: 'confetti',
      label: say('ui.variants.ledWall.confetti'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.22,
    },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 3, step: 0.015, standard: 0.6 },
    {
      key: 'gain',
      label: say('ui.variants.ledWall.panelGain'),
      min: 0.05,
      max: 5,
      step: 0.05,
      standard: 1,
    },
    { key: 'contrast', label: say('common.contrast'), min: 0.15, max: 10, step: 0.05, standard: 1 },
  ],
  colours: [
    { key: 'lit', label: say('ui.variants.ledWall.litTile'), standard: '#fff2dd' },
    { key: 'wall', label: say('ui.variants.ledWall.wall'), standard: '#161616' },
  ],
};

export { LED_WALL };
