import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const MEADOW: OrbVariant = {
  key: 'meadow',
  label: say('ui.variants.meadow.meadow'),
  shader: say('ui.variants.meadow.defineAA2FloatDrosteHazeFloat'),
  params: [
    {
      key: 'fall',
      label: say('ui.variants.meadow.fallSpeed'),
      min: 0,
      max: 4,
      step: 0.01,
      standard: 0.12,
      isRate: true,
    },
    {
      key: 'tilt',
      label: say('ui.variants.meadow.frameTilt'),
      min: -1.6,
      max: 1.6,
      step: 0.01,
      standard: 0,
    },
    {
      key: 'drift',
      label: say('ui.variants.meadow.weatherDrift'),
      min: 0,
      max: 4,
      step: 0.02,
      standard: 0.2,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    {
      key: 'scale',
      label: say('ui.variants.meadow.tunnelScale'),
      min: 0.3,
      max: 20,
      step: 0.1,
      standard: 4.5,
    },
    {
      key: 'bulge',
      label: say('ui.variants.meadow.domeBulge'),
      min: 0,
      max: 4,
      step: 0.02,
      standard: 0.2,
    },
    {
      key: 'ratio',
      label: say('ui.variants.meadow.frameRatio'),
      min: 1.1,
      max: 6,
      step: 0.02,
      standard: 3.06,
    },
    {
      key: 'horizon',
      label: say('ui.variants.meadow.horizon'),
      min: -0.9,
      max: 0.9,
      step: 0.01,
      standard: -0.11,
    },
    {
      key: 'cloudScale',
      label: say('common.cloudScale'),
      min: 0.1,
      max: 8,
      step: 0.05,
      standard: 1.2,
    },
    {
      key: 'cloudCover',
      label: say('ui.variants.meadow.cloudCover'),
      min: 0.02,
      max: 0.98,
      step: 0.01,
      standard: 0.42,
    },
    {
      key: 'streakFreq',
      label: say('ui.variants.meadow.wallDetail'),
      min: 0.2,
      max: 20,
      step: 0.1,
      standard: 2.9,
    },
    {
      key: 'streakRad',
      label: say('ui.variants.meadow.smear'),
      min: 0.02,
      max: 4,
      step: 0.02,
      standard: 0.54,
    },
    { key: 'water', label: say('common.water'), min: 0, max: 1, step: 0.01, standard: 0 },
    {
      key: 'flowerScale',
      label: say('ui.variants.meadow.flowerScale'),
      min: 2,
      max: 120,
      step: 1,
      standard: 24,
    },
    {
      key: 'flowerDensity',
      label: say('ui.variants.meadow.flowerDensity'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.27,
    },
    {
      key: 'flowerSize',
      label: say('ui.variants.meadow.flowerSize'),
      min: 0.05,
      max: 0.6,
      step: 0.01,
      standard: 0.43,
    },
    {
      key: 'frameShade',
      label: say('ui.variants.meadow.frameShading'),
      min: 0.2,
      max: 1.4,
      step: 0.01,
      standard: 0.62,
    },
    {
      key: 'haze',
      label: say('ui.variants.meadow.aerialHaze'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.8,
    },
    {
      key: 'hazeRange',
      label: say('ui.variants.meadow.hazeReach'),
      min: 0.005,
      max: 1.5,
      step: 0.005,
      standard: 0.09,
    },
    { key: 'gain', label: say('common.brightness'), min: 0.05, max: 4, step: 0.02, standard: 1.38 },
    {
      key: 'contrast',
      label: say('common.contrast'),
      min: 0.15,
      max: 10,
      step: 0.05,
      standard: 1.05,
    },
    {
      key: 'saturation',
      label: say('common.saturation'),
      min: 0,
      max: 4,
      step: 0.02,
      standard: 1.56,
    },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 3, step: 0.015, standard: 0.345 },
    { key: 'rim', label: say('common.rimSheen'), min: 0, max: 3, step: 0.015, standard: 0.555 },
  ],
  colours: [
    { key: 'sky', label: say('ui.variants.meadow.sky'), standard: '#4a92e0' },
    { key: 'cloud', label: say('common.cloud'), standard: '#f7fbff' },
    { key: 'canopy', label: say('ui.variants.meadow.canopy'), standard: '#12401f' },
    { key: 'meadow', label: say('ui.variants.meadow.meadow'), standard: '#5aa63a' },
    { key: 'water', label: say('common.water'), standard: '#156f6a' },
    { key: 'bloom', label: say('ui.variants.meadow.bloom'), standard: '#ff6a3a' },
    { key: 'sheen', label: say('common.sheen'), standard: '#cfe6ff' },
  ],
};

export { MEADOW };
