import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const ORBITAL: OrbVariant = {
  key: 'orbital',
  label: say('ui.variants.orbital.orbital'),
  shader: say('ui.variants.orbital.constFloatPI314159265359Void'),
  params: [
    {
      key: 'speed',
      label: say('common.animSpeed'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 0.9,
      isRate: true,
    },
    {
      key: 'rotSpeed',
      label: say('ui.variants.orbital.rotationSpeed'),
      min: 0,
      max: 5,
      step: 0.05,
      standard: 0.5,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    { key: 'swell', label: say('common.inputSwell'), min: 0, max: 1, step: 0.01, standard: 0.07 },
    {
      key: 'posScale',
      label: say('ui.variants.orbital.orbitalZoom'),
      min: 0.15,
      max: 10,
      step: 0.05,
      standard: 0.5,
    },
    {
      key: 'flowSpeed',
      label: say('ui.variants.orbital.flowSpeed'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.35,
      isRate: true,
    },
    {
      key: 'flowAmp',
      label: say('ui.variants.orbital.flowAmount'),
      min: 0,
      max: 4,
      step: 0.05,
      standard: 0.45,
    },
    {
      key: 'flowScale',
      label: say('ui.variants.orbital.flowScale'),
      min: 0.3,
      max: 10,
      step: 0.1,
      standard: 0.3,
    },
    {
      key: 'precess',
      label: say('ui.variants.orbital.precession'),
      min: 0,
      max: 4,
      step: 0.05,
      standard: 0.3,
    },
    {
      key: 'radialPow',
      label: say('ui.variants.orbital.radialPower'),
      min: 0.5,
      max: 15,
      step: 0.1,
      standard: 0.5,
    },
    {
      key: 'radialDecay',
      label: say('ui.variants.orbital.radialDecay'),
      min: 0.3,
      max: 30,
      step: 0.15,
      standard: 1,
    },
    {
      key: 'probPow',
      label: say('ui.variants.orbital.probabilityCurve'),
      min: 0.1,
      max: 3,
      step: 0.015,
      standard: 0.4,
    },
    {
      key: 'probGain',
      label: say('ui.variants.orbital.probabilityGain'),
      min: 0.15,
      max: 15,
      step: 0.1,
      standard: 3,
    },
    {
      key: 'waveFreq',
      label: say('ui.variants.orbital.waveFrequency'),
      min: 0,
      max: 20,
      step: 0.5,
      standard: 4,
    },
    {
      key: 'chromaSpread',
      label: say('ui.variants.orbital.chromaSpread'),
      min: 0,
      max: 1.5,
      step: 0.01,
      standard: 0.18,
    },
    { key: 'glow', label: say('common.glow'), min: 0, max: 5, step: 0.05, standard: 0.9 },
    {
      key: 'metalDark',
      label: say('ui.variants.orbital.metalDarkness'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 0,
    },
    {
      key: 'baseVis',
      label: say('ui.variants.orbital.baseVisibility'),
      min: 0,
      max: 1.5,
      step: 0.01,
      standard: 0.12,
    },
  ],
  colours: [],
};

export { ORBITAL };
