import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const PLASMA: OrbVariant = {
  key: 'plasma',
  label: say('ui.variants.plasma.plasma'),
  shader: say('ui.variants.plasma.defineSTEPS64FloatIonSharpFloat'),
  params: [
    {
      key: 'speed',
      label: say('common.animSpeed'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 1,
      isRate: true,
    },
    {
      key: 'spin',
      label: say('ui.variants.plasma.spinRate'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.2,
      isRate: true,
    },
    {
      key: 'camDist',
      label: say('common.cameraDistance'),
      min: 1,
      max: 50,
      step: 0.3,
      standard: 7,
    },
    { key: 'focal', label: say('common.lens'), min: 0.15, max: 15, step: 0.1, standard: 2.25 },
    {
      key: 'envRadius',
      label: say('ui.variants.plasma.globeRadius'),
      min: 0.15,
      max: 15,
      step: 0.1,
      standard: 2.6,
    },
    { key: 'swell', label: say('common.inputSwell'), min: 0, max: 1, step: 0.01, standard: 0.15 },
    {
      key: 'tilt',
      label: say('ui.variants.plasma.axisTilt'),
      min: 0,
      max: 4,
      step: 0.02,
      standard: 0.4,
    },
    {
      key: 'fils',
      label: say('ui.variants.plasma.filamentDensity'),
      min: 0.5,
      max: 12,
      step: 0.1,
      standard: 6,
    },
    {
      key: 'writhe',
      label: say('ui.variants.plasma.writhe'),
      min: 0,
      max: 3,
      step: 0.02,
      standard: 0.9,
    },
    {
      key: 'writheFreq',
      label: say('ui.variants.plasma.writheFrequency'),
      min: 0.2,
      max: 8,
      step: 0.05,
      standard: 1.6,
    },
    {
      key: 'sharp',
      label: say('ui.variants.plasma.arcSharpness'),
      min: 0.5,
      max: 60,
      step: 0.5,
      standard: 4,
    },
    {
      key: 'soft',
      label: say('ui.variants.plasma.arcCoreSoftness'),
      min: 0.002,
      max: 0.5,
      step: 0.002,
      standard: 0.06,
    },
    {
      key: 'whiten',
      label: say('ui.variants.plasma.coreWhitening'),
      min: 0,
      max: 0.2,
      step: 0.002,
      standard: 0.008,
    },
    {
      key: 'coreGain',
      label: say('ui.variants.plasma.nucleusGlow'),
      min: 0,
      max: 5,
      step: 0.05,
      standard: 1.6,
    },
    {
      key: 'tipGain',
      label: say('ui.variants.plasma.glassFlare'),
      min: 0,
      max: 6,
      step: 0.05,
      standard: 1.8,
    },
    {
      key: 'fill',
      label: say('ui.variants.plasma.bodyHaze'),
      min: 0,
      max: 2,
      step: 0.01,
      standard: 0.02,
    },
    {
      key: 'stepClamp',
      label: say('ui.variants.plasma.stepClamp'),
      min: 0.3,
      max: 300,
      step: 1.5,
      standard: 40,
    },
    {
      key: 'scatter',
      label: say('ui.variants.plasma.diffusion'),
      min: 0,
      max: 0.5,
      step: 0.003,
      standard: 0.012,
    },
    { key: 'exposure', label: say('common.exposure'), min: 0.1, max: 200, step: 0.5, standard: 11 },
    { key: 'contrast', label: say('common.contrast'), min: 0.15, max: 15, step: 0.1, standard: 1 },
    {
      key: 'saturation',
      label: say('common.saturation'),
      min: 0,
      max: 4,
      step: 0.02,
      standard: 1.2,
    },
    {
      key: 'alphaGain',
      label: say('common.alphaGain'),
      min: 0.05,
      max: 15,
      step: 0.1,
      standard: 2.5,
    },
    { key: 'edge', label: say('common.edgeSharpness'), min: 0, max: 1, step: 0.01, standard: 1 },
  ],
  colours: [
    { key: 'inner', label: say('ui.variants.plasma.nucleus'), standard: '#ff70d8' },
    { key: 'arc', label: say('ui.variants.plasma.arc'), standard: '#5a5cff' },
    { key: 'tint', label: say('common.tint'), standard: '#ffffff' },
  ],
};

export { PLASMA };
