import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const RADAR: OrbVariant = {
  key: 'radar',
  label: say('ui.variants.radar.radar'),
  shader: say('ui.variants.radar.defineVORTICES6DefineFBM3OCT'),
  params: [
    {
      key: 'speed',
      label: say('ui.variants.radar.frontSpeed'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 1,
      isRate: true,
    },
    {
      key: 'spin',
      label: say('common.roll'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.27,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    {
      key: 'scale',
      label: say('ui.variants.radar.gridZoom'),
      min: 0.3,
      max: 8,
      step: 0.05,
      standard: 2.4,
    },
    { key: 'cells', label: say('ui.variants.radar.grid'), min: 8, max: 120, step: 1, standard: 34 },
    {
      key: 'dot',
      label: say('ui.variants.radar.dotSize'),
      min: 0.1,
      max: 0.5,
      step: 0.01,
      standard: 0.36,
    },
    {
      key: 'swirl',
      label: say('ui.variants.radar.swirl'),
      min: 0,
      max: 8,
      step: 0.05,
      standard: 1.5,
    },
    {
      key: 'vortex',
      label: say('ui.variants.radar.vortexSize'),
      min: 0.1,
      max: 2,
      step: 0.01,
      standard: 0.45,
    },
    {
      key: 'freq',
      label: say('ui.variants.radar.stormScale'),
      min: 0.2,
      max: 8,
      step: 0.05,
      standard: 1.6,
    },
    {
      key: 'warp',
      label: say('ui.variants.radar.bend'),
      min: 0,
      max: 3,
      step: 0.02,
      standard: 0.5,
    },
    {
      key: 'lo',
      label: say('ui.variants.radar.quietThreshold'),
      min: 0,
      max: 1,
      step: 0.005,
      standard: 0.12,
    },
    {
      key: 'hi',
      label: say('ui.variants.radar.peakThreshold'),
      min: 0,
      max: 1,
      step: 0.005,
      standard: 0.82,
    },
    {
      key: 'curve',
      label: say('ui.variants.radar.responseCurve'),
      min: 0.5,
      max: 4,
      step: 0.05,
      standard: 1.4,
    },
    {
      key: 'dither',
      label: say('ui.variants.radar.classDither'),
      min: 0,
      max: 0.6,
      step: 0.005,
      standard: 0.12,
    },
    {
      key: 'sparse',
      label: say('ui.variants.radar.quietDensity'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.16,
    },
    {
      key: 'density',
      label: say('ui.variants.radar.fill'),
      min: 0,
      max: 1.5,
      step: 0.01,
      standard: 1,
    },
    { key: 'twinkle', label: say('common.twinkleRate'), min: 0, max: 30, step: 0.5, standard: 3 },
    { key: 'grain', label: say('common.paperGrain'), min: 0, max: 1, step: 0.01, standard: 0.1 },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 1, step: 0.01, standard: 0.18 },
    { key: 'rim', label: say('common.rim'), min: 0, max: 1, step: 0.01, standard: 0.35 },
  ],
  colours: [
    { key: 'paper', label: say('common.paper'), standard: '#efe9dc' },
    { key: 'c0', label: say('ui.variants.radar.quiet'), standard: '#a9a9a6' },
    { key: 'c1', label: say('ui.variants.radar.class1'), standard: '#2e5df0' },
    { key: 'c2', label: say('ui.variants.radar.class2'), standard: '#38d9ec' },
    { key: 'c3', label: say('ui.variants.radar.class3'), standard: '#22c35c' },
    { key: 'c4', label: say('ui.variants.radar.class4'), standard: '#e8322a' },
    { key: 'c5', label: say('ui.variants.radar.class5'), standard: '#f5d020' },
    { key: 'c6', label: say('ui.variants.radar.peak'), standard: '#e030c0' },
  ],
};

export { RADAR };
