import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const STORM: OrbVariant = {
  key: 'storm',
  label: say('ui.variants.storm.storm'),
  shader: say('ui.variants.storm.constFloatPI314159265359Float'),
  params: [
    {
      key: 'speed',
      label: say('ui.variants.storm.stormSpeed'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 0.9,
      isRate: true,
    },
    {
      key: 'spin',
      label: say('common.roll'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.12,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    {
      key: 'scale',
      label: say('ui.variants.storm.weatherScale'),
      min: 0.3,
      max: 12,
      step: 0.1,
      standard: 2.4,
    },
    {
      key: 'bands',
      label: say('ui.variants.storm.bandCount'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 6,
    },
    {
      key: 'shear',
      label: say('ui.variants.storm.bandShear'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 1.1,
    },
    { key: 'warp', label: say('common.warp'), min: 0, max: 8, step: 0.05, standard: 2.2 },
    { key: 'churn', label: say('common.churn'), min: 0, max: 8, step: 0.05, standard: 1.4 },
    { key: 'gain', label: say('common.brightness'), min: 0.05, max: 5, step: 0.05, standard: 1.15 },
    {
      key: 'contrast',
      label: say('common.contrast'),
      min: 0.15,
      max: 10,
      step: 0.05,
      standard: 1.35,
    },
    {
      key: 'grain',
      label: say('ui.variants.storm.fieldGrain'),
      min: 0,
      max: 2,
      step: 0.01,
      standard: 0.4,
    },
    {
      key: 'filmGrain',
      label: say('ui.variants.storm.filmGrain'),
      min: 0,
      max: 2,
      step: 0.01,
      standard: 0.35,
    },
    { key: 'grainSize', label: say('common.grainSize'), min: 1, max: 8, step: 1, standard: 2 },
    {
      key: 'rainbow',
      label: say('ui.variants.storm.iridescence'),
      min: 0,
      max: 2,
      step: 0.01,
      standard: 0.65,
    },
    {
      key: 'flashRate',
      label: say('ui.variants.storm.flashRate'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 1.6,
    },
    {
      key: 'flash',
      label: say('ui.variants.storm.flashPower'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.7,
    },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 3, step: 0.015, standard: 0.85 },
    { key: 'rim', label: say('common.rimLight'), min: 0, max: 3, step: 0.015, standard: 0.5 },
  ],
  colours: [
    { key: 'deep', label: say('common.deep'), standard: '#2a0f4e' },
    { key: 'low', label: say('ui.variants.storm.lowPressure'), standard: '#0fd0c3' },
    { key: 'mid', label: say('ui.variants.storm.midPressure'), standard: '#ff5e9d' },
    { key: 'hot', label: say('ui.variants.storm.highPressure'), standard: '#ffd166' },
    { key: 'flash', label: say('ui.variants.storm.lightning'), standard: '#eaf4ff' },
  ],
};

export { STORM };
