import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const TERMINAL: OrbVariant = {
  key: 'terminal',
  label: say('ui.variants.terminal.terminal'),
  shader: say('ui.variants.terminal.voidMainFloatDensBiasUPDensity'),
  params: [
    {
      key: 'drift',
      label: say('common.drift'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.55,
      isRate: true,
    },
    {
      key: 'scroll',
      label: say('common.scroll'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.05,
      isRate: true,
    },
    {
      key: 'speed',
      label: say('ui.variants.terminal.pulseRate'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 0.52,
      isRate: true,
    },
    { key: 'pulse', label: say('common.pulseDepth'), min: 0, max: 2, step: 0.01, standard: 0 },
    {
      key: 'spin',
      label: say('common.roll'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.12,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    {
      key: 'cells',
      label: say('ui.variants.terminal.glyphGrid'),
      min: 16,
      max: 120,
      step: 2,
      standard: 68,
    },
    {
      key: 'scale',
      label: say('ui.variants.terminal.fieldScale'),
      min: 0.3,
      max: 10,
      step: 0.1,
      standard: 5.1,
    },
    {
      key: 'density',
      label: say('ui.variants.terminal.glyphDensity'),
      min: 0,
      max: 2,
      step: 0.01,
      standard: 0.31,
    },
    {
      key: 'dropout',
      label: say('ui.variants.terminal.dropout'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.24,
    },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 3, step: 0.015, standard: 1.11 },
    {
      key: 'rim',
      label: say('ui.variants.terminal.rimGlow'),
      min: 0,
      max: 3,
      step: 0.015,
      standard: 0.66,
    },
    {
      key: 'gain',
      label: say('ui.variants.terminal.phosphorGain'),
      min: 0.05,
      max: 5,
      step: 0.05,
      standard: 0.9,
    },
    { key: 'contrast', label: say('common.contrast'), min: 0.15, max: 10, step: 0.05, standard: 1 },
  ],
  colours: [
    { key: 'glow', label: say('common.glow'), standard: '#6a57ff' },
    { key: 'deep', label: say('common.deep'), standard: '#0b3b2d' },
  ],
};

export { TERMINAL };
