import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const THERMAL: OrbVariant = {
  key: 'thermal',
  label: say('ui.variants.thermal.thermal'),
  shader: say('ui.variants.thermal.constFloatPI314159265359Float'),
  params: [
    {
      key: 'speed',
      label: say('common.drift'),
      min: 0.015,
      max: 10,
      step: 0.05,
      standard: 0.5,
      isRate: true,
    },
    {
      key: 'spin',
      label: say('common.roll'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.05,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 0.9 },
    { key: 'scale', label: say('common.zoom'), min: 0.3, max: 8, step: 0.05, standard: 3 },
    {
      key: 'freq',
      label: say('ui.variants.thermal.poolScale'),
      min: 0.2,
      max: 6,
      step: 0.05,
      standard: 1.4,
    },
    { key: 'warp', label: say('common.warp'), min: 0, max: 3, step: 0.02, standard: 0.6 },
    {
      key: 'lo',
      label: say('ui.variants.thermal.coldThreshold'),
      min: 0,
      max: 1,
      step: 0.005,
      standard: 0.42,
    },
    {
      key: 'hi',
      label: say('ui.variants.thermal.hotThreshold'),
      min: 0,
      max: 1,
      step: 0.005,
      standard: 0.74,
    },
    {
      key: 'gain',
      label: say('ui.variants.thermal.heatGain'),
      min: 0.1,
      max: 6,
      step: 0.02,
      standard: 1,
    },
    {
      key: 'jitter',
      label: say('ui.variants.thermal.heatJitter'),
      min: 0,
      max: 0.5,
      step: 0.005,
      standard: 0.015,
    },
    {
      key: 'bands',
      label: say('ui.variants.thermal.contourBands'),
      min: 2,
      max: 24,
      step: 1,
      standard: 7,
    },
    {
      key: 'banding',
      label: say('ui.variants.thermal.contourStrength'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.85,
    },
    { key: 'contrast', label: say('common.contrast'), min: 0.3, max: 3, step: 0.02, standard: 1 },
    {
      key: 'dither',
      label: say('ui.variants.thermal.dither'),
      min: 0,
      max: 0.6,
      step: 0.005,
      standard: 0.05,
    },
    {
      key: 'dots',
      label: say('ui.variants.thermal.screenPitch'),
      min: 4,
      max: 120,
      step: 1,
      standard: 46,
    },
    {
      key: 'dotGain',
      label: say('ui.variants.thermal.dotGain'),
      min: 0.2,
      max: 2,
      step: 0.01,
      standard: 1,
    },
    {
      key: 'dotSoft',
      label: say('ui.variants.thermal.dotSoftness'),
      min: 0.01,
      max: 0.3,
      step: 0.005,
      standard: 0.12,
    },
    {
      key: 'misregister',
      label: say('ui.variants.thermal.misregistration'),
      min: 0,
      max: 3,
      step: 0.02,
      standard: 0.5,
    },
    {
      key: 'ink',
      label: say('ui.variants.thermal.inkDensity'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.92,
    },
    {
      key: 'printMix',
      label: say('ui.variants.thermal.printMix'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.28,
    },
    { key: 'grain', label: say('common.paperGrain'), min: 0, max: 2, step: 0.01, standard: 0.35 },
    { key: 'grainSize', label: say('common.grainSize'), min: 1, max: 8, step: 1, standard: 2 },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 1, step: 0.01, standard: 0.25 },
    { key: 'rim', label: say('common.rimLight'), min: 0, max: 3, step: 0.015, standard: 0.25 },
  ],
  colours: [
    { key: 'cold', label: say('ui.variants.thermal.cold'), standard: '#0b0a1e' },
    { key: 'cool', label: say('ui.variants.thermal.cool'), standard: '#3b2a9a' },
    { key: 'warm', label: say('ui.variants.thermal.warm'), standard: '#f05a28' },
    { key: 'hot', label: say('ui.variants.thermal.hot'), standard: '#f6b53a' },
    { key: 'core', label: say('common.core'), standard: '#fff1e6' },
    { key: 'paper', label: say('common.paper'), standard: '#f4ecdf' },
  ],
};

export { THERMAL };
