import type { OrbVariant } from '@ValenceUI/orbs/OrbVariant';
import { say } from '@ValenceI18n/say';

const VOXEL_WORLD: OrbVariant = {
  key: 'voxelWorld',
  label: say('ui.variants.voxelWorld.voxelWorld'),
  shader: say('ui.variants.voxelWorld.defineSTEPS160Vec3CkDriftFloat'),
  params: [
    {
      key: 'spin',
      label: say('common.spin'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.22,
      isRate: true,
    },
    { key: 'tilt', label: say('common.tilt'), min: 0, max: 4, step: 0.02, standard: 0.45 },
    {
      key: 'drift',
      label: say('ui.variants.voxelWorld.terrainDrift'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.12,
      isRate: true,
    },
    {
      key: 'season',
      label: say('ui.variants.voxelWorld.seasonRate'),
      min: 0,
      max: 10,
      step: 0.05,
      standard: 0.3,
      isRate: true,
    },
    {
      key: 'shuffle',
      label: say('ui.variants.voxelWorld.emberRate'),
      min: 0,
      max: 20,
      step: 0.1,
      standard: 0.8,
      isRate: true,
    },
    { key: 'radius', label: say('common.radius'), min: 0.15, max: 3, step: 0.015, standard: 1.15 },
    {
      key: 'blocks',
      label: say('ui.variants.voxelWorld.blocks'),
      min: 16,
      max: 96,
      step: 1,
      standard: 64,
    },
    {
      key: 'rough',
      label: say('ui.variants.voxelWorld.mountains'),
      min: 0,
      max: 0.8,
      step: 0.01,
      standard: 0.45,
    },
    {
      key: 'scale',
      label: say('ui.variants.voxelWorld.terrainScale'),
      min: 0.5,
      max: 8,
      step: 0.05,
      standard: 2.4,
    },
    {
      key: 'sea',
      label: say('ui.variants.voxelWorld.seaLevel'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.5,
    },
    {
      key: 'trees',
      label: say('ui.variants.voxelWorld.trees'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.75,
    },
    {
      key: 'cave',
      label: say('ui.variants.voxelWorld.caves'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.4,
    },
    {
      key: 'ore',
      label: say('ui.variants.voxelWorld.oreDensity'),
      min: 0,
      max: 0.6,
      step: 0.01,
      standard: 0.12,
    },
    {
      key: 'glow',
      label: say('ui.variants.voxelWorld.oreGlow'),
      min: 0,
      max: 5,
      step: 0.03,
      standard: 0.9,
    },
    {
      key: 'core',
      label: say('ui.variants.voxelWorld.moltenCore'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.5,
    },
    {
      key: 'texture',
      label: say('ui.variants.voxelWorld.textureGrain'),
      min: 0,
      max: 1,
      step: 0.01,
      standard: 0.6,
    },
    { key: 'light', label: say('common.keyLight'), min: 0, max: 3, step: 0.015, standard: 1 },
    { key: 'gain', label: say('common.gain'), min: 0.05, max: 5, step: 0.05, standard: 1 },
    { key: 'contrast', label: say('common.contrast'), min: 0.15, max: 10, step: 0.05, standard: 1 },
  ],
  colours: [
    { key: 'grass', label: say('ui.variants.voxelWorld.grass'), standard: '#6abe30' },
    { key: 'dirt', label: say('ui.variants.voxelWorld.mud'), standard: '#6f4a2f' },
    { key: 'stone', label: say('ui.variants.voxelWorld.stone'), standard: '#8a8a90' },
    { key: 'sand', label: say('ui.variants.voxelWorld.sand'), standard: '#dbcf9c' },
    { key: 'water', label: say('common.water'), standard: '#2f66d0' },
    { key: 'leaf', label: say('ui.variants.voxelWorld.leaves'), standard: '#3e8f27' },
    { key: 'ore', label: say('ui.variants.voxelWorld.ore'), standard: '#4de3ff' },
    { key: 'lava', label: say('ui.variants.voxelWorld.lava'), standard: '#ff7b26' },
  ],
};

export { VOXEL_WORLD };
