ALTER TABLE "valence_requests"."blocklisted_release" ALTER COLUMN "reason" SET DATA TYPE jsonb USING CASE WHEN "reason" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "reason", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."indexer" ALTER COLUMN "last_problem" SET DATA TYPE jsonb USING CASE WHEN "last_problem" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "last_problem", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."indexer" ALTER COLUMN "turned_off_because" SET DATA TYPE jsonb USING CASE WHEN "turned_off_because" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "turned_off_because", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."media_request" ALTER COLUMN "refused_because" SET DATA TYPE jsonb USING CASE WHEN "refused_because" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "refused_because", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."media_request" ALTER COLUMN "problem" SET DATA TYPE jsonb USING CASE WHEN "problem" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "problem", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."request_item" ALTER COLUMN "problem" SET DATA TYPE jsonb USING CASE WHEN "problem" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "problem", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."request_log" ALTER COLUMN "message" SET DATA TYPE jsonb USING CASE WHEN "message" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "message", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."download" ALTER COLUMN "problem" SET DATA TYPE jsonb USING CASE WHEN "problem" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "problem", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."download" ALTER COLUMN "filing_problem" SET DATA TYPE jsonb USING CASE WHEN "filing_problem" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "filing_problem", 'values', '{}'::jsonb) END;--> statement-breakpoint
ALTER TABLE "valence_requests"."download_event" ALTER COLUMN "problem" SET DATA TYPE jsonb USING CASE WHEN "problem" IS NULL THEN NULL ELSE jsonb_build_object('code', NULL, 'message', "problem", 'values', '{}'::jsonb) END;