const HOST_METHODS = [
  'settings.read',
  'log.info',
  'log.warn',
  'log.error',
  'storage.get',
  'storage.set',
  'storage.delete',
  'storage.keys',
  'http.fetch',
  'accounts.connection',
  'accounts.disconnect',
  'profiles.list',
  'library.search',
  'library.findByExternalId',
  'library.episodes',
  'viewing.progress',
  'viewing.markWatched',
  'viewing.markUnwatched',
  'requests.searchCatalogue',
  'requests.create',
  'playlists.list',
  'playlists.create',
  'playlists.add',
  'music.findTrack',
  'notifications.send',
] as const;

export { HOST_METHODS };
