import { describe, expect, it } from 'vitest';
import { parseReleaseName } from './parseReleaseName';
import type { ParsedRelease } from '@ValenceContracts/schemas/ParsedRelease';

const REAL_NAMES: [string, Partial<ParsedRelease>][] = [
  [
    'Inception (2010 ITA/ENG) [1080p x265] [Paso77]',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'Paso77',
    },
  ],
  [
    'Inception (2010) 1080p 10bit BluRay [Org DVD Hindi DD5.1 + English DDP5.1] x265 HEVC ESub ANNi',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'Inception (2010) 1080p BluRay x264 DTS HD MA Soup',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'Inception (2010) 1080p MAX WEB-DL [EN TR] DDP5.1 H.264-TURG',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: 'TURG',
    },
  ],
  [
    'Inception (2010) 2160p UHD HDR Bluray AV1 Opus Multi7 [dAV1nci]',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'bluray',
      codec: 'av1',
      hdr: ['hdr10'],
      group: 'dAV1nci',
    },
  ],
  [
    'Inception (2010) AC3 5.1 ITA.ENG 2160p H265 HDR10 sub NUita.eng MIRCrew',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: null,
      codec: 'h265',
      hdr: ['hdr10'],
      group: null,
    },
  ],
  [
    'Inception (2010) [SDR] 2160p BluRay HEVC [Hin Eng] DDP 5.1 — PeruGuy',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'Inception 2010 1080p 10bit 60FPS BDRip x265 HEVC Org Hindi DVD 5 1 448Kbps English AAC 5 1 ESub-MrStrange',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: 'MrStrange',
    },
  ],
  [
    'Inception 2010 1080p BluRay HEVC x265 5.1 BONE',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'Inception 2010 1080p BluRay REGRADED DS4K SDR x265 10Bit HEVC Eng DDP 5.1 Hin DD 5.1 DDP 2.0-VITOENCODES',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: 'VITOENCODES',
    },
  ],
  [
    'Inception 2010 1080p BluRay x265 Hindi DD5.1 English DD5.1 ESub SP3LL',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'Inception 2010 PROPER Bluray 2160p AV1 HDR10 EN/ITA/FR/ES/DE OPUS 5.1-UH',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'bluray',
      codec: 'av1',
      hdr: ['hdr10'],
      group: 'UH',
      isProper: true,
    },
  ],
  [
    'Inception 2010 UHD BluRay 2160p DTS HD MA 5 1 DV HEVC HYBRID REMUX-FraMeSToR',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['dolbyVision'],
      group: 'FraMeSToR',
    },
  ],
  [
    'Inception 2010 UHD BluRay 2160p HDR10 DV HEVC DTS HD MA 5.1 x265-E',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'E',
    },
  ],
  [
    'Inception.2010.1080p.10bit.DS4K.BluRay.[Org.DDP2. Hindi+DDP5.1 English].ESub.HEVC The.PunisheR',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'Inception.2010.1080p.3D.FULL SBS.HEVC.ENG HUN.iFA-AI3D',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'AI3D',
    },
  ],
  [
    'Inception.2010.1080p.AMZN.WEB-DL.DDP.5.1.H.264-PiRaTeS',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: 'PiRaTeS',
    },
  ],
  [
    'Inception.2010.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: 'GalaxyRG265',
    },
  ],
  [
    'Inception.2010.1080p.MAX.WEB-DL.DDP.5.1.H.265-PiRaTeS',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'webdl',
      codec: 'h265',
      group: 'PiRaTeS',
    },
  ],
  [
    'Inception.2010.2160p.BluRay.REMUX.HEVC.DTS HD.MA.5.1-FGT',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      group: 'FGT',
    },
  ],
  [
    'Inception.2010.2160p.HDR10.BDRip.DDP5.1.x265.BluBit',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['hdr10'],
      group: null,
    },
  ],
  [
    'Inception.2010.2160p.MAX.WEB-DL.DDP5.1.DV.HDR.H.265-TURG',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'TURG',
    },
  ],
  [
    'Inception.2010.BluRay.1080p.AC3.ITA.AC3.ENG.x264 Wiggaz.mkv',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'Inception.2010.ITA.ENG.UHDrip.HDR.HEVC.2160p.mkv',
    {
      title: 'Inception',
      year: 2010,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['hdr10'],
      group: null,
    },
  ],
  [
    'Inception.2010.iTA ENG.Bluray.1080p.HDR.x265 CYBER.mkv',
    {
      title: 'Inception',
      year: 2010,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['hdr10'],
      group: null,
    },
  ],
  [
    'One Piece - 1100 - 1080p WEB x264 -NanDesuKa (CR).mkv',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'One Piece - 1100 - 720p WEB x264 -NanDesuKa (CR).mkv',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '720p',
      source: 'webdl',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'One Piece S01E1100 VOSTFR 1080p WEB x264 AAC -Tsundere-Raws (CR)',
    {
      title: 'One Piece',
      year: null,
      seasons: [1],
      episodes: [1100],
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'One Piece S01E1100 VOSTFR 720p WEB x264 AAC -Tsundere-Raws (CR)',
    {
      title: 'One Piece',
      year: null,
      seasons: [1],
      episodes: [1100],
      resolution: '720p',
      source: 'webdl',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'Oppenheimer (2023 ITA/ENG) [1080p x265] [IMAX] [Paso77]',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: null,
      codec: 'h265',
      edition: 'IMAX',
      group: 'Paso77',
    },
  ],
  [
    'Oppenheimer (2023) (1080p BluRay x265 HEVC 10bit AAC 5.1 Vyndros)',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'Oppenheimer (2023) (1080p DS4K BluRay x265 10 bit HDR AAC 7.1) [WeSLeY]',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['hdr10'],
      group: 'WeSLeY',
    },
  ],
  [
    'Oppenheimer (2023) 1080p BluRay x264 DTS HD MA A4',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'Oppenheimer (2023) 1080p NF WEB-DL [EN TR] DDP5.1 H.264-TURG',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: 'TURG',
    },
  ],
  [
    'Oppenheimer (2023) IMAX 2160p UHD HDR BluRay VVenC H.266 VVC AAC 5.1 [RAV1NE]',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h266',
      hdr: ['hdr10'],
      edition: 'IMAX',
      group: 'RAV1NE',
    },
  ],
  [
    'Oppenheimer 2023 1080p [PortalGoods]',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: null,
      codec: null,
      group: 'PortalGoods',
    },
  ],
  [
    'Oppenheimer 2023 2160p H265 HDR10 DV ITA DTS 7 1 EAC3 ITA ENG AC3 5.1 Sub Ita Eng Raffyone-iDN_CreW',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: null,
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'iDN_CreW',
    },
  ],
  [
    'Oppenheimer 2023 4K UHD IMAX BluRay 2160p HDR DTS HD MA 5.1 H.265-MgB',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['hdr10'],
      edition: 'IMAX',
      group: 'MgB',
    },
  ],
  [
    'Oppenheimer 2023 Bluray 2160p AV1 HDR10 EN/FR/ES OPUS 5.1-UH',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'bluray',
      codec: 'av1',
      hdr: ['hdr10'],
      group: 'UH',
    },
  ],
  [
    'Oppenheimer 2023 IMAX 1080p DS4K MA WEBRip DD+ 5.1 x265-AnoZu',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'webrip',
      codec: 'h265',
      edition: 'IMAX',
      group: 'AnoZu',
    },
  ],
  [
    'Oppenheimer 2023 IMAX 2160p 4K Hybrid UHD HDR10 DV Blu ray REMUX Dual Audio Hindi English ESub-RemuxDoc',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'remux',
      codec: null,
      hdr: ['dolbyVision', 'hdr10'],
      edition: 'IMAX',
      group: 'RemuxDoc',
    },
  ],
  [
    'Oppenheimer 2023 IMAX UHD BluRay 2160p DV HEVC HDR10+ DTS HD MA 5.1 x265-E',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10plus'],
      edition: 'IMAX',
      group: 'E',
    },
  ],
  [
    'Oppenheimer 2023 IMAX UHD BluRay HDR 2160p ITA DTS ITA AAC ENG DTS HD MA ENG AC3 Subs x265 TbZ-mkv',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['hdr10'],
      edition: 'IMAX',
      group: null,
    },
  ],
  [
    'Oppenheimer 2023 UHD BluRay 2160p DV HEVC HDR10+ DTS HD Master Audio 5.1 x265-E',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10plus'],
      group: 'E',
    },
  ],
  [
    'Oppenheimer.2023.1080p.IMAX.BluRay.x265.AAC5.1-GYPSY',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      edition: 'IMAX',
      group: 'GYPSY',
    },
  ],
  [
    'Oppenheimer.2023.2160p.MA.WEB-DL.DUAL.DTS.HD.MA.5.1+DD+5.1.DV HDR.H.265-TheBiscuitMan',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'TheBiscuitMan',
    },
  ],
  [
    'Oppenheimer.2023.IMAX.4K.HDR.DV.2160p BDRemux Ita Eng x265-NAHOM',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      edition: 'IMAX',
      group: 'NAHOM',
    },
  ],
  [
    'Oppenheimer.2023.IMAX.Blu ray.1080p.DS4K.10bit.HEVC.[Org.Hindi.DDP5.1 English.DDP5.1].ESub-NmCT',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      edition: 'IMAX',
      group: 'NmCT',
    },
  ],
  [
    'Oppenheimer.2023.IMAX.BluRay.1080p.DTS.x264-PRoDJi',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      edition: 'IMAX',
      group: 'PRoDJi',
    },
  ],
  [
    'Oppenheimer.2023.UHD.BluRay.2160p.DTS HD.MA.5.1.DV.HEVC.HYBRID.REMUX-FraMeSToR',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['dolbyVision'],
      group: 'FraMeSToR',
    },
  ],
  [
    'Oppenheimer.2023.bluray.sdr.movie.1080p.av1.2.0.opus.1900mb-Rosy',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'av1',
      group: 'Rosy',
    },
  ],
  [
    'Oppenheimer.2023.bluray.sdr.movie.1080p.av1.5.1.opus.4500mb.vmaf-Rosy',
    {
      title: 'Oppenheimer',
      year: 2023,
      resolution: '1080p',
      source: 'bluray',
      codec: 'av1',
      group: 'Rosy',
    },
  ],
  [
    'Oppenheimer.The.Real.Story.2023.1080p.WEBRip.DDP5.1.x265.10bit-GalaxyRG265',
    {
      title: 'Oppenheimer The Real Story',
      year: 2023,
      resolution: '1080p',
      source: 'webrip',
      codec: 'h265',
      group: 'GalaxyRG265',
    },
  ],
  [
    'The Matrix (1999) +Extras x264 Mkv DVDrip [ET777]',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: null,
      source: 'dvd',
      codec: 'h264',
      group: 'ET777',
    },
  ],
  [
    'The Matrix (1999) 1080p BluRay Regraded x264 TrueHD Atmos 7.1 [lvl99]',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: 'lvl99',
    },
  ],
  [
    'The Matrix (1999) 1080p H265 BluRay Rip ita eng AC3 5.1 sub ita eng Licdom',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'The Matrix (1999) 2160P Ai Upscaled Open Matte Webdl 60FPS 10BIT SDR H265 7.1 Marjenbo',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      edition: 'Open Matte',
      group: null,
    },
  ],
  [
    'The Matrix (1999) 2160p H265 BluRay Rip 10 bit DV HDR10+ ita eng AC3 5.1 sub ita eng Licdom',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10plus'],
      group: null,
    },
  ],
  [
    'The Matrix (1999) DVDRip NonyMovies',
    { title: 'The Matrix', year: 1999, resolution: null, source: 'dvd', codec: null, group: null },
  ],
  [
    'The Matrix 1999 BluRay 1080p DTS AC3 x264-MgB',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: 'MgB',
    },
  ],
  [
    'The Matrix 1999 BluRay 1080p DTS HD MA 5.1 AC3 x264-MgB',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: 'MgB',
    },
  ],
  [
    'The Matrix 1999 UHD BluRay 2160p DV HEVC TrueHD.Atmos.7.1-E',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      hdr: ['dolbyVision'],
      group: 'E',
    },
  ],
  [
    'The Matrix 1999 UHD BluRay 2160p TrueHD Atmos 7 1 DV HEVC REMUX-FraMeSToR',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['dolbyVision'],
      group: 'FraMeSToR',
    },
  ],
  [
    'The Matrix 4 Movies Collection 1999 2021 1080p 10bit 60FPS BluRay x265 HEVC Org NF Hindi DDP 5.1 640Kbps English AAC 5 1 ESub-MrStrange',
    {
      title: 'The Matrix 4 Movies Collection',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: 'MrStrange',
    },
  ],
  [
    'The Matrix.1999.2160p.DV.HDR10.WEB-DL.DDP5.1.x265.BluBit',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: null,
    },
  ],
  [
    'The Office (2005 2013) Complete Series Superfan Episodes 1080p BluRay Rip 10Bit H265 AAC 5.1',
    {
      title: 'The Office',
      year: 2005,
      isCompleteSeries: true,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'The Office US S01 S09 1080p BluRay REMUX DTS HD MA 5.1 AVC MiXED [RiCK]',
    {
      title: 'The Office US',
      year: null,
      seasons: [1, 2, 3, 4, 5, 6, 7, 8, 9],
      resolution: '1080p',
      source: 'remux',
      codec: 'h264',
      group: 'RiCK',
    },
  ],
  [
    'The.Matrix.1999.1080p.3D.FULL SBS.HEVC.ENG HUN.iFA-AI3D',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'AI3D',
    },
  ],
  [
    'The.Matrix.1999.1080p.BluRay.AV1.DDP5.1.Multi4-dAV1nci',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'av1',
      group: 'dAV1nci',
    },
  ],
  [
    'The.Matrix.1999.1080p.BluRay.DDP5.1.x265.10bit-GalaxyRG265',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: 'GalaxyRG265',
    },
  ],
  [
    'The.Matrix.1999.1080p.BluRay.Denoised.AV1.DDP5.1.Multi4-dAV1nci',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'av1',
      group: 'dAV1nci',
    },
  ],
  [
    'The.Matrix.1999.2160p.HDR.UHD.BluRay.AV1.DDP5.1.Atmos.Multi4-dAV1nci',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'bluray',
      codec: 'av1',
      hdr: ['hdr10'],
      group: 'dAV1nci',
    },
  ],
  [
    'The.Matrix.1999.2160p.MAX.WEB-DL.DDPA.5.1.DV.HDR.H.265-PiRaTeS[TGx]',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'PiRaTeS',
    },
  ],
  [
    'The.Matrix.1999.4K.HDR.DV.2160p.BDRemux Ita Eng x265-NAHOM',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'NAHOM',
    },
  ],
  [
    'The.Matrix.1999.HDTV.Hybrid.OPEN MATTE.1080p.x265.10Bit.HEVC.(Eng AAC 7.1 Hin DDP 5.1).VITOENCODES',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'hdtv',
      codec: 'h265',
      edition: 'OPEN MATTE',
      group: null,
    },
  ],
  [
    'The.Matrix.1999.REPACK.4K.HDR.DV.2160p.BDRemux Ita Eng x265-NAHOM',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'NAHOM',
      isRepack: true,
    },
  ],
  [
    'The.Matrix.1999.Remastered.1080p.BluRay.x264-RiPRG',
    {
      title: 'The Matrix',
      year: 1999,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      edition: 'Remastered',
      group: 'RiPRG',
    },
  ],
  [
    'The.Matrix.Collection.1999 2021.2160p.UHD.BDRIP.x265.AC3-AOC',
    {
      title: 'The Matrix Collection',
      year: 1999,
      resolution: '2160p',
      source: 'bluray',
      codec: 'h265',
      group: 'AOC',
    },
  ],
  [
    'Toilet bound Hanako kun S02E18 Severance 1080p CR WEB-DL AAC2.0 H 264-VARYG (Jibaku Shounen Hanako-kun, Multi-Subs)',
    {
      title: 'Toilet bound Hanako kun',
      year: null,
      seasons: [2],
      episodes: [18],
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: null,
    },
  ],
  [
    'Toilet bound Hanako kun S02E18 Severance 1080p CR WEB-DL DUAL AAC2.0 H 264-VARYG (Jibaku Shounen Hanako-kun, Dual-Audio, Multi-Subs)',
    {
      title: 'Toilet bound Hanako kun',
      year: null,
      seasons: [2],
      episodes: [18],
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: null,
    },
  ],
  [
    '[ASW] One Piece - 1100 [1080p HEVC x265 10Bit][AAC]',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'ASW',
    },
  ],
  [
    '[Anime Land] One Piece 1100 (WEBRip 1080p Hi10P AAC) RAW [C3E7F3CF].mp4',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: 'webrip',
      codec: 'h264',
      group: 'Anime Land',
    },
  ],
  [
    '[Anime Time] One Piece - 1100 [1080p][HEVC 10bit x265][AAC][Eng Sub] [Weekly]',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'Anime Time',
    },
  ],
  [
    '[CameEsp] One Piece - 1100 [1080p][ESP-ENG][mkv]',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: null,
      group: 'CameEsp',
    },
  ],
  [
    '[CameEsp] One Piece - 1100 [720p][ESP-ENG][mkv]',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '720p',
      source: null,
      codec: null,
      group: 'CameEsp',
    },
  ],
  [
    '[Erai-raws] One Piece - 1100 [1080p][HEVC][Multiple Subtitle] [ENG][POR-BR][SPA-LA][SPA][ARA][FRE][GER][ITA]',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'Erai-raws',
    },
  ],
  [
    '[Judas] One Piece - 1100 [1080p][HEVC x265 10bit][Multi-Subs] (Weekly)',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'Judas',
    },
  ],
  [
    '[Kaerizaki-Fansub]_One_Piece_1100_[VERSION_LIGHT][VOSTFR][FHD_1920x1080].mp4',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: null,
      group: 'Kaerizaki-Fansub',
    },
  ],
  [
    '[Kaerizaki-Fansub]_One_Piece_1100_[VOSTFR][FHD_1920x1080].mp4',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: null,
      group: 'Kaerizaki-Fansub',
    },
  ],
  [
    '[Kaerizaki-Fansub]_One_Piece_1100_[VOSTFR][HD_1280x720].mp4',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '720p',
      source: null,
      codec: null,
      group: 'Kaerizaki-Fansub',
    },
  ],
  [
    '[Kaerizaki-Fansub]_One_Piece_1100_[VOSTFR][HD_1280x720][10Bits].mkv',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '720p',
      source: null,
      codec: null,
      group: 'Kaerizaki-Fansub',
    },
  ],
  [
    '[Kaerizaki-Fansub]_One_Piece_1100_[VOSTFR][SD_854x480].mp4',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '480p',
      source: null,
      codec: null,
      group: 'Kaerizaki-Fansub',
    },
  ],
  [
    '[KiyoshiiSubs] One Piece -1100 [1080p][H.265 - 10Bit].mkv',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: 'h265',
      group: 'KiyoshiiSubs',
    },
  ],
  [
    '[Naruto-Kun.Hu] One Piece - 1100 [1080p].mkv',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: null,
      group: 'Naruto-Kun.Hu',
    },
  ],
  [
    '[RedDeadProject] One Piece - 1100 & 1101 - [JPBD] [HEVC] [x265]',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100, 1101],
      resolution: null,
      source: 'bluray',
      codec: 'h265',
      group: 'RedDeadProject',
    },
  ],
  [
    '[Ricky Gervais] The Office (2001 2003) (UK) Complete Series DVDRip',
    {
      title: 'The Office',
      year: 2001,
      isCompleteSeries: true,
      resolution: null,
      source: 'dvd',
      codec: null,
      group: 'Ricky Gervais',
    },
  ],
  [
    '[ToonsHub] One Piece - E1100 Powers on a Different Level! Luffy vs. Lucci! 2160p B-Global WEB-DL x264 (Multi-Subs)',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '2160p',
      source: 'webdl',
      codec: 'h264',
      group: 'ToonsHub',
    },
  ],
  [
    '[ToonsHub] One Piece - Saga 15 - Egghead S01E1100 1080p ADN WEB-DL x264 (French-Sub)',
    {
      title: 'One Piece - Saga 15 - Egghead',
      year: null,
      seasons: [1],
      episodes: [1100],
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: 'ToonsHub',
    },
  ],
  [
    '[Valenciano] One Piece - 1100 [1080p][AV1 10bit][AAC][Multi-Sub] (Weekly).mkv',
    {
      title: 'One Piece',
      year: null,
      absoluteEpisodes: [1100],
      resolution: '1080p',
      source: null,
      codec: 'av1',
      group: 'Valenciano',
    },
  ],
  [
    'Pink Floyd - The Dark Side of the Moon (1973) [FLAC 24-96]',
    {
      title: 'Pink Floyd - The Dark Side of the Moon',
      year: 1973,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'flac24',
      group: null,
    },
  ],
  [
    'Pink Floyd - The Dark Side Of The Moon (50th Anniversary Edition) (2023) [24Bit-192kHz] FLAC [PMEDIA]',
    {
      title: 'Pink Floyd - The Dark Side Of The Moon (50th Anniversary Edition)',
      year: 2023,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'flac24',
      edition: '50th Anniversary Edition',
      group: 'PMEDIA',
    },
  ],
  [
    'Daft Punk - Discovery (2001) [MP3 320]',
    {
      title: 'Daft Punk - Discovery',
      year: 2001,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'mp3-320',
      group: null,
    },
  ],
  [
    'Daft Punk - Random Access Memories (2013) MP3 V0',
    {
      title: 'Daft Punk - Random Access Memories',
      year: 2013,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'mp3-v0',
      group: null,
    },
  ],
  [
    "Taylor Swift - 1989 (Taylor's Version) (2023) Mp3 320kbps [PMEDIA]",
    {
      title: "Taylor Swift - 1989 (Taylor's Version)",
      year: 2023,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'mp3-320',
      edition: "Taylor's Version",
      group: 'PMEDIA',
    },
  ],
  [
    'Kendrick Lamar - GNX (2024) [AAC 256]',
    {
      title: 'Kendrick Lamar - GNX',
      year: 2024,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'aac',
      group: null,
    },
  ],
  [
    'Beyonce - Renaissance (2022) [24-48] ALAC',
    {
      title: 'Beyonce - Renaissance',
      year: 2022,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'alac',
      group: null,
    },
  ],
  [
    "Various Artists - Now That's What I Call Music 100 (2018) Opus",
    {
      title: "Various Artists - Now That's What I Call Music 100",
      year: 2018,
      resolution: null,
      source: null,
      codec: null,
      musicQuality: 'opus',
      group: null,
    },
  ],
  [
    'Severance.S02E01.Hello.Ms.Cobel.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX',
    {
      title: 'Severance',
      year: null,
      seasons: [2],
      episodes: [1],
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'FLUX',
    },
  ],
  [
    'The.Bear.S03.COMPLETE.1080p.HULU.WEB-DL.DDP5.1.H.264-NTb',
    {
      title: 'The Bear',
      year: null,
      seasons: [3],
      resolution: '1080p',
      source: 'webdl',
      codec: 'h264',
      group: 'NTb',
    },
  ],
  [
    'Breaking.Bad.S05E14.Ozymandias.1080p.BluRay.x264-ROVERS',
    {
      title: 'Breaking Bad',
      year: null,
      seasons: [5],
      episodes: [14],
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: 'ROVERS',
    },
  ],
  [
    'Shogun.2024.S01E10.A.Dream.of.a.Dream.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX',
    {
      title: 'Shogun',
      year: 2024,
      seasons: [1],
      episodes: [10],
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10'],
      group: 'FLUX',
    },
  ],
  [
    'Friends.S01E01E02.1080p.BluRay.x265-RARBG',
    {
      title: 'Friends',
      year: null,
      seasons: [1],
      episodes: [1, 2],
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: 'RARBG',
    },
  ],
  [
    'Friends.S01E01-E03.720p.WEBRip.x264-GROUP',
    {
      title: 'Friends',
      year: null,
      seasons: [1],
      episodes: [1, 2, 3],
      resolution: '720p',
      source: 'webrip',
      codec: 'h264',
      group: 'GROUP',
    },
  ],
  [
    'Doctor.Who.2005.S01E01.Rose.720p.BluRay.x264-SHORTBREHD',
    {
      title: 'Doctor Who',
      year: 2005,
      seasons: [1],
      episodes: [1],
      resolution: '720p',
      source: 'bluray',
      codec: 'h264',
      group: 'SHORTBREHD',
    },
  ],
  [
    'Game of Thrones Season 1-8 Complete 1080p BluRay x265',
    {
      title: 'Game of Thrones',
      year: null,
      seasons: [1, 2, 3, 4, 5, 6, 7, 8],
      resolution: '1080p',
      source: 'bluray',
      codec: 'h265',
      group: null,
    },
  ],
  [
    'The.Simpsons.1x05.Bart.the.General.DVDRip.XviD-SAiNTS',
    {
      title: 'The Simpsons',
      year: null,
      seasons: [1],
      episodes: [5],
      resolution: null,
      source: 'dvd',
      codec: 'xvid',
      group: 'SAiNTS',
    },
  ],
  [
    'Blade.Runner.2049.2017.2160p.UHD.BluRay.REMUX.HDR.HEVC.Atmos-EPSiLON',
    {
      title: 'Blade Runner 2049',
      year: 2017,
      resolution: '2160p',
      source: 'remux',
      codec: 'h265',
      hdr: ['hdr10'],
      group: 'EPSiLON',
    },
  ],
  [
    '1917.2019.1080p.BluRay.x264-SPARKS',
    {
      title: '1917',
      year: 2019,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      group: 'SPARKS',
    },
  ],
  [
    '2012.2009.PROPER.720p.BluRay.x264-SiNNERS',
    {
      title: '2012',
      year: 2009,
      resolution: '720p',
      source: 'bluray',
      codec: 'h264',
      group: 'SiNNERS',
      isProper: true,
    },
  ],
  [
    'The.Lord.of.the.Rings.The.Fellowship.of.the.Ring.2001.EXTENDED.1080p.BluRay.x264-SiNNERS',
    {
      title: 'The Lord of the Rings The Fellowship of the Ring',
      year: 2001,
      resolution: '1080p',
      source: 'bluray',
      codec: 'h264',
      edition: 'EXTENDED',
      group: 'SiNNERS',
    },
  ],
  [
    'Dune.Part.Two.2024.REPACK.2160p.MA.WEB-DL.DDP5.1.Atmos.DV.HDR10+.H.265-FLUX',
    {
      title: 'Dune Part Two',
      year: 2024,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10plus'],
      group: 'FLUX',
      isRepack: true,
    },
  ],
  [
    'Alien.Romulus.2024.HDCAM.x264-NoGroup',
    {
      title: 'Alien Romulus',
      year: 2024,
      resolution: null,
      source: 'cam',
      codec: 'h264',
      group: 'NoGroup',
    },
  ],
  [
    'Deadpool.and.Wolverine.2024.1080p.HDTS.x264-XYZ',
    {
      title: 'Deadpool and Wolverine',
      year: 2024,
      resolution: '1080p',
      source: 'telesync',
      codec: 'h264',
      group: 'XYZ',
    },
  ],
];

describe('parseReleaseName', () => {
  it.each(REAL_NAMES)('reads %s', (name, expected) => {
    expect(parseReleaseName(name)).toMatchObject(expected);
  });

  it('reads everything a name gives in one place', () => {
    expect(
      parseReleaseName(
        'Dune.Part.Two.2024.REPACK.2160p.MA.WEB-DL.DDP5.1.Atmos.DV.HDR10+.H.265-FLUX',
      ),
    ).toEqual({
      title: 'Dune Part Two',
      year: 2024,
      seasons: [],
      episodes: [],
      absoluteEpisodes: [],
      airDate: null,
      isCompleteSeries: false,
      resolution: '2160p',
      source: 'webdl',
      codec: 'h265',
      hdr: ['dolbyVision', 'hdr10plus'],
      audio: ['atmos', 'eac3'],
      audioChannels: '5.1',
      musicQuality: null,
      languages: [],
      edition: null,
      group: 'FLUX',
      isProper: false,
      isRepack: true,
    });
  });

  it('reads a daily show by the day it aired', () => {
    expect(
      parseReleaseName('The.Daily.Show.2024.03.14.Jon.Stewart.720p.WEB.h264-EDITH').airDate,
    ).toBe('2024-03-14');
  });

  it('reads a long run of anime episodes', () => {
    expect(
      parseReleaseName('[Sick-Fansubs] One Piece 1100-1155 [1080p]').absoluteEpisodes,
    ).toHaveLength(56);
  });
});
